"""Fix: Book index

Revision ID: 4d9a54d76964
Revises: c429d0188318
Create Date: 2025-09-30 23:15:59.518566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4d9a54d76964'
down_revision: Union[str, Sequence[str], None] = 'c429d0188318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_deleted'), table_name='book')
    op.create_index(op.f('ix_book_id_user'), 'book', ['id_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_id_user'), table_name='book')
    op.create_index(op.f('ix_book_deleted'), 'book', ['deleted'], unique=False)
    # ### end Alembic commands ###
